### ISSUE TITLE
getStories() function never gets called

### ISSUE THREAD

**Issue by csyvian** [ashwin-sureshkumar/angular-infinite-scroller#1]
Hi Ashwin,

I tried to implement this infinite-scroller in a sample project i created but, when i load the page, getStories() function never gets called(no error on console either). Is there anything i am missing?

Thanks,
Shiv

**Comment by ashwin-sureshkumar** [comment]
@csyvian - Please make sure in the `infinite-scroller.directive.ts` line no: 77 is below. That is the block of code which sets the immediate start, also make sure you have `immediateCallback` attribute set to `true`

```
    if (this.immediateCallback) {
      this.requestOnScroll$ = this.requestOnScroll$
        .startWith([DEFAULT_SCROLL_POSITION, DEFAULT_SCROLL_POSITION]);
    }
```

```  
<ul 
    id="infinite-scroller"  
    appInfiniteScroller 
    scrollPerecnt="70" 
    immediateCallback="true" 
     [scrollCallback]="scrollCallback">
    <li *ngFor="let item of news">{{item.title}}</li>
  </ul>
```

**Comment by csyvian** [comment]
immediateCallback is set to true and line 77 is also in the directive and it gets executed at first run also but somehow, not sure what, getStories() function never gets called. If you can spare few minutes, i can send you directive, component, service and html file.

**Comment by ashwin-sureshkumar** [comment]
@csyvian - Sure, can you create a plunker or jsbin. Would be easier ?
