### ISSUE TITLE
Does this open source so that any one can use?

### ISSUE THREAD

**Issue by iampratapak** [ashwin-sureshkumar/angular-infinite-scroller#4]
May I know the license for this please?
Is it allowed to use this code in other applications?

**Comment by ashwin-sureshkumar** [comment]
This was written for a blog post, I haven't published as a library which I am eventually planning to do. 

So use as you need, I will add an MIT license on to this one. Would appreciate if you could share the blog post and pass on credits so it can reach many others. Hopefully it was helpfully to you.
